maestroApiKeyPath: ./secrets/maestro-token-dev
turboSubmit: false

networkId: preprod
logging:
  - type:
      tag: stderr
    severity: Debug
    verbosity: V2

fundMnemonicPath: ./secrets/beacon-mnemonic-dev.yaml

fundAccIx: 0
fundAddrIx: 0

otherSignatories: []

requiredSignatures: 1

tokenName: "7a6b466f6c64"

policyId: "982beb80d155358fad5c3b0015c4b13f7d7341835246af037009d73a"

updateInterval: 120

tokensToMint: 1
